/********************************************************************************
** Form generated from reading UI file 'mainwindowmFTMbc.ui'
**
** Created by: Qt User Interface Compiler version 5.12.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef MAINWINDOWMFTMBC_H
#define MAINWINDOWMFTMBC_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTableView>
#include <QtWidgets/QTableWidget>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionNew_Character;
    QAction *actionSave_Character;
    QAction *actionLoad_Character;
    QAction *actionExit;
    QAction *actionAbout;
    QAction *actionAbout_Qt;
    QAction *actionSave_As;
    QWidget *centralwidget;
    QLineEdit *nameInputField;
    QLineEdit *organizationInputField;
    QLineEdit *CampaignInputField;
    QLabel *label;
    QSpinBox *HarmCurrentField;
    QSpinBox *HarmThresholdField;
    QLabel *label_2;
    QSpinBox *StressCurrentField;
    QSpinBox *StressThresholdField;
    QLabel *label_3;
    QLabel *label_4;
    QSpinBox *MentalHarmCurrentField;
    QSpinBox *MentalHarmThresholdField;
    QSpinBox *SpiritualHarmCurrentField;
    QSpinBox *SpiritualHarmThresholdField;
    QLabel *label_5;
    QLineEdit *WillpowerField;
    QLabel *label_6;
    QLineEdit *HeatField;
    QLabel *label_7;
    QLineEdit *FavorField;
    QLabel *label_8;
    QPushButton *AddCoresButton;
    QLabel *label_9;
    QPushButton *AddSpellButton;
    QTableWidget *tableWidget;
    QTableWidget *tableWidget_2;
    QLabel *label_10;
    QLabel *label_11;
    QLabel *label_12;
    QLabel *label_13;
    QLabel *label_14;
    QLabel *label_15;
    QLabel *label_16;
    QLabel *label_17;
    QSpinBox *StrBaseField;
    QSpinBox *PerBaseField;
    QSpinBox *EndBaseField;
    QSpinBox *ChaBaseField;
    QSpinBox *IntBaseField;
    QSpinBox *AgiBaseField;
    QSpinBox *LucBaseField;
    QSpinBox *spinBox_8;
    QSpinBox *spinBox_9;
    QSpinBox *spinBox_10;
    QSpinBox *spinBox_11;
    QSpinBox *spinBox_12;
    QSpinBox *spinBox_13;
    QSpinBox *spinBox_14;
    QSpinBox *spinBox_15;
    QSpinBox *spinBox_16;
    QSpinBox *spinBox_17;
    QSpinBox *spinBox_18;
    QSpinBox *spinBox_19;
    QSpinBox *spinBox_20;
    QSpinBox *spinBox_21;
    QSpinBox *StrField;
    QSpinBox *PerField;
    QSpinBox *EndField;
    QSpinBox *ChaField;
    QSpinBox *IntField;
    QSpinBox *AgiField;
    QSpinBox *LucField;
    QLabel *label_18;
    QTextEdit *textEdit;
    QSpinBox *TotalActionsField;
    QPushButton *pushButton;
    QSpinBox *UsedActionsField;
    QLabel *label_19;
    QLabel *label_20;
    QCheckBox *checkBox;
    QLabel *label_21;
    QCheckBox *checkBox_2;
    QCheckBox *checkBox_3;
    QCheckBox *checkBox_4;
    QCheckBox *checkBox_5;
    QCheckBox *checkBox_6;
    QCheckBox *checkBox_7;
    QCheckBox *checkBox_8;
    QTableWidget *tableWidget_3;
    QTableWidget *tableWidget_4;
    QTableWidget *tableWidget_5;
    QTableView *tableView;
    QLabel *label_22;
    QLabel *label_23;
    QLabel *label_24;
    QPushButton *pushButton_2;
    QLabel *label_25;
    QSpinBox *CurrentDayField;
    QLabel *label_26;
    QSpinBox *spinBox;
    QSpinBox *TotalDaysField;
    QLabel *label_27;
    QLabel *label_28;
    QSpinBox *NumberOfActionsField1;
    QLabel *label_29;
    QLabel *label_30;
    QLabel *label_31;
    QLineEdit *lineEdit_4;
    QLineEdit *lineEdit_5;
    QLineEdit *lineEdit_6;
    QMenuBar *menubar;
    QMenu *menuFile;
    QMenu *menuHelp;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1919, 909);
        actionNew_Character = new QAction(MainWindow);
        actionNew_Character->setObjectName(QString::fromUtf8("actionNew_Character"));
        actionSave_Character = new QAction(MainWindow);
        actionSave_Character->setObjectName(QString::fromUtf8("actionSave_Character"));
        actionLoad_Character = new QAction(MainWindow);
        actionLoad_Character->setObjectName(QString::fromUtf8("actionLoad_Character"));
        actionExit = new QAction(MainWindow);
        actionExit->setObjectName(QString::fromUtf8("actionExit"));
        actionAbout = new QAction(MainWindow);
        actionAbout->setObjectName(QString::fromUtf8("actionAbout"));
        actionAbout_Qt = new QAction(MainWindow);
        actionAbout_Qt->setObjectName(QString::fromUtf8("actionAbout_Qt"));
        actionSave_As = new QAction(MainWindow);
        actionSave_As->setObjectName(QString::fromUtf8("actionSave_As"));
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        nameInputField = new QLineEdit(centralwidget);
        nameInputField->setObjectName(QString::fromUtf8("nameInputField"));
        nameInputField->setGeometry(QRect(0, 0, 113, 32));
        organizationInputField = new QLineEdit(centralwidget);
        organizationInputField->setObjectName(QString::fromUtf8("organizationInputField"));
        organizationInputField->setGeometry(QRect(0, 30, 113, 32));
        CampaignInputField = new QLineEdit(centralwidget);
        CampaignInputField->setObjectName(QString::fromUtf8("CampaignInputField"));
        CampaignInputField->setGeometry(QRect(0, 60, 113, 32));
        label = new QLabel(centralwidget);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(200, 0, 41, 21));
        HarmCurrentField = new QSpinBox(centralwidget);
        HarmCurrentField->setObjectName(QString::fromUtf8("HarmCurrentField"));
        HarmCurrentField->setGeometry(QRect(190, 20, 52, 32));
        HarmThresholdField = new QSpinBox(centralwidget);
        HarmThresholdField->setObjectName(QString::fromUtf8("HarmThresholdField"));
        HarmThresholdField->setGeometry(QRect(190, 50, 52, 32));
        HarmThresholdField->setValue(4);
        label_2 = new QLabel(centralwidget);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(280, 0, 58, 18));
        StressCurrentField = new QSpinBox(centralwidget);
        StressCurrentField->setObjectName(QString::fromUtf8("StressCurrentField"));
        StressCurrentField->setGeometry(QRect(280, 20, 52, 32));
        StressThresholdField = new QSpinBox(centralwidget);
        StressThresholdField->setObjectName(QString::fromUtf8("StressThresholdField"));
        StressThresholdField->setGeometry(QRect(280, 50, 52, 32));
        StressThresholdField->setValue(10);
        label_3 = new QLabel(centralwidget);
        label_3->setObjectName(QString::fromUtf8("label_3"));
        label_3->setGeometry(QRect(360, 0, 91, 18));
        label_4 = new QLabel(centralwidget);
        label_4->setObjectName(QString::fromUtf8("label_4"));
        label_4->setGeometry(QRect(470, 0, 101, 18));
        MentalHarmCurrentField = new QSpinBox(centralwidget);
        MentalHarmCurrentField->setObjectName(QString::fromUtf8("MentalHarmCurrentField"));
        MentalHarmCurrentField->setGeometry(QRect(360, 20, 52, 32));
        MentalHarmThresholdField = new QSpinBox(centralwidget);
        MentalHarmThresholdField->setObjectName(QString::fromUtf8("MentalHarmThresholdField"));
        MentalHarmThresholdField->setGeometry(QRect(360, 50, 52, 32));
        SpiritualHarmCurrentField = new QSpinBox(centralwidget);
        SpiritualHarmCurrentField->setObjectName(QString::fromUtf8("SpiritualHarmCurrentField"));
        SpiritualHarmCurrentField->setGeometry(QRect(470, 20, 52, 32));
        SpiritualHarmThresholdField = new QSpinBox(centralwidget);
        SpiritualHarmThresholdField->setObjectName(QString::fromUtf8("SpiritualHarmThresholdField"));
        SpiritualHarmThresholdField->setGeometry(QRect(470, 50, 52, 32));
        label_5 = new QLabel(centralwidget);
        label_5->setObjectName(QString::fromUtf8("label_5"));
        label_5->setGeometry(QRect(190, 90, 71, 18));
        WillpowerField = new QLineEdit(centralwidget);
        WillpowerField->setObjectName(QString::fromUtf8("WillpowerField"));
        WillpowerField->setGeometry(QRect(190, 110, 61, 32));
        label_6 = new QLabel(centralwidget);
        label_6->setObjectName(QString::fromUtf8("label_6"));
        label_6->setGeometry(QRect(280, 90, 58, 18));
        HeatField = new QLineEdit(centralwidget);
        HeatField->setObjectName(QString::fromUtf8("HeatField"));
        HeatField->setGeometry(QRect(280, 110, 41, 32));
        label_7 = new QLabel(centralwidget);
        label_7->setObjectName(QString::fromUtf8("label_7"));
        label_7->setGeometry(QRect(360, 90, 58, 18));
        FavorField = new QLineEdit(centralwidget);
        FavorField->setObjectName(QString::fromUtf8("FavorField"));
        FavorField->setGeometry(QRect(360, 110, 41, 32));
        label_8 = new QLabel(centralwidget);
        label_8->setObjectName(QString::fromUtf8("label_8"));
        label_8->setGeometry(QRect(590, 0, 58, 18));
        AddCoresButton = new QPushButton(centralwidget);
        AddCoresButton->setObjectName(QString::fromUtf8("AddCoresButton"));
        AddCoresButton->setGeometry(QRect(590, 20, 71, 34));
        label_9 = new QLabel(centralwidget);
        label_9->setObjectName(QString::fromUtf8("label_9"));
        label_9->setGeometry(QRect(950, 0, 58, 18));
        AddSpellButton = new QPushButton(centralwidget);
        AddSpellButton->setObjectName(QString::fromUtf8("AddSpellButton"));
        AddSpellButton->setGeometry(QRect(950, 20, 88, 34));
        tableWidget = new QTableWidget(centralwidget);
        tableWidget->setObjectName(QString::fromUtf8("tableWidget"));
        tableWidget->setGeometry(QRect(670, 0, 256, 192));
        tableWidget_2 = new QTableWidget(centralwidget);
        tableWidget_2->setObjectName(QString::fromUtf8("tableWidget_2"));
        tableWidget_2->setGeometry(QRect(1040, 0, 256, 192));
        label_10 = new QLabel(centralwidget);
        label_10->setObjectName(QString::fromUtf8("label_10"));
        label_10->setGeometry(QRect(1350, 0, 58, 18));
        label_11 = new QLabel(centralwidget);
        label_11->setObjectName(QString::fromUtf8("label_11"));
        label_11->setGeometry(QRect(1390, 0, 31, 18));
        label_12 = new QLabel(centralwidget);
        label_12->setObjectName(QString::fromUtf8("label_12"));
        label_12->setGeometry(QRect(1390, 50, 31, 18));
        label_13 = new QLabel(centralwidget);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(1390, 100, 31, 18));
        label_14 = new QLabel(centralwidget);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(1390, 150, 31, 18));
        label_15 = new QLabel(centralwidget);
        label_15->setObjectName(QString::fromUtf8("label_15"));
        label_15->setGeometry(QRect(1390, 200, 31, 18));
        label_16 = new QLabel(centralwidget);
        label_16->setObjectName(QString::fromUtf8("label_16"));
        label_16->setGeometry(QRect(1390, 250, 31, 18));
        label_17 = new QLabel(centralwidget);
        label_17->setObjectName(QString::fromUtf8("label_17"));
        label_17->setGeometry(QRect(1390, 300, 31, 18));
        StrBaseField = new QSpinBox(centralwidget);
        StrBaseField->setObjectName(QString::fromUtf8("StrBaseField"));
        StrBaseField->setGeometry(QRect(1390, 20, 52, 32));
        StrBaseField->setValue(1);
        PerBaseField = new QSpinBox(centralwidget);
        PerBaseField->setObjectName(QString::fromUtf8("PerBaseField"));
        PerBaseField->setGeometry(QRect(1390, 70, 52, 32));
        PerBaseField->setValue(1);
        EndBaseField = new QSpinBox(centralwidget);
        EndBaseField->setObjectName(QString::fromUtf8("EndBaseField"));
        EndBaseField->setGeometry(QRect(1390, 120, 52, 32));
        EndBaseField->setValue(1);
        ChaBaseField = new QSpinBox(centralwidget);
        ChaBaseField->setObjectName(QString::fromUtf8("ChaBaseField"));
        ChaBaseField->setGeometry(QRect(1390, 170, 52, 32));
        ChaBaseField->setValue(1);
        IntBaseField = new QSpinBox(centralwidget);
        IntBaseField->setObjectName(QString::fromUtf8("IntBaseField"));
        IntBaseField->setGeometry(QRect(1390, 220, 52, 32));
        IntBaseField->setValue(1);
        AgiBaseField = new QSpinBox(centralwidget);
        AgiBaseField->setObjectName(QString::fromUtf8("AgiBaseField"));
        AgiBaseField->setGeometry(QRect(1390, 270, 52, 32));
        AgiBaseField->setValue(1);
        LucBaseField = new QSpinBox(centralwidget);
        LucBaseField->setObjectName(QString::fromUtf8("LucBaseField"));
        LucBaseField->setGeometry(QRect(1390, 320, 52, 32));
        LucBaseField->setValue(1);
        spinBox_8 = new QSpinBox(centralwidget);
        spinBox_8->setObjectName(QString::fromUtf8("spinBox_8"));
        spinBox_8->setGeometry(QRect(1440, 20, 52, 32));
        spinBox_9 = new QSpinBox(centralwidget);
        spinBox_9->setObjectName(QString::fromUtf8("spinBox_9"));
        spinBox_9->setGeometry(QRect(1440, 70, 52, 32));
        spinBox_10 = new QSpinBox(centralwidget);
        spinBox_10->setObjectName(QString::fromUtf8("spinBox_10"));
        spinBox_10->setGeometry(QRect(1440, 120, 52, 32));
        spinBox_11 = new QSpinBox(centralwidget);
        spinBox_11->setObjectName(QString::fromUtf8("spinBox_11"));
        spinBox_11->setGeometry(QRect(1440, 170, 52, 32));
        spinBox_12 = new QSpinBox(centralwidget);
        spinBox_12->setObjectName(QString::fromUtf8("spinBox_12"));
        spinBox_12->setGeometry(QRect(1440, 220, 52, 32));
        spinBox_13 = new QSpinBox(centralwidget);
        spinBox_13->setObjectName(QString::fromUtf8("spinBox_13"));
        spinBox_13->setGeometry(QRect(1440, 270, 52, 32));
        spinBox_14 = new QSpinBox(centralwidget);
        spinBox_14->setObjectName(QString::fromUtf8("spinBox_14"));
        spinBox_14->setGeometry(QRect(1440, 320, 52, 32));
        spinBox_15 = new QSpinBox(centralwidget);
        spinBox_15->setObjectName(QString::fromUtf8("spinBox_15"));
        spinBox_15->setGeometry(QRect(1490, 20, 52, 32));
        spinBox_16 = new QSpinBox(centralwidget);
        spinBox_16->setObjectName(QString::fromUtf8("spinBox_16"));
        spinBox_16->setGeometry(QRect(1490, 70, 52, 32));
        spinBox_17 = new QSpinBox(centralwidget);
        spinBox_17->setObjectName(QString::fromUtf8("spinBox_17"));
        spinBox_17->setGeometry(QRect(1490, 120, 52, 32));
        spinBox_18 = new QSpinBox(centralwidget);
        spinBox_18->setObjectName(QString::fromUtf8("spinBox_18"));
        spinBox_18->setGeometry(QRect(1490, 170, 52, 32));
        spinBox_19 = new QSpinBox(centralwidget);
        spinBox_19->setObjectName(QString::fromUtf8("spinBox_19"));
        spinBox_19->setGeometry(QRect(1490, 220, 52, 32));
        spinBox_20 = new QSpinBox(centralwidget);
        spinBox_20->setObjectName(QString::fromUtf8("spinBox_20"));
        spinBox_20->setGeometry(QRect(1490, 270, 52, 32));
        spinBox_21 = new QSpinBox(centralwidget);
        spinBox_21->setObjectName(QString::fromUtf8("spinBox_21"));
        spinBox_21->setGeometry(QRect(1490, 320, 52, 32));
        StrField = new QSpinBox(centralwidget);
        StrField->setObjectName(QString::fromUtf8("StrField"));
        StrField->setGeometry(QRect(1540, 20, 52, 32));
        StrField->setValue(1);
        PerField = new QSpinBox(centralwidget);
        PerField->setObjectName(QString::fromUtf8("PerField"));
        PerField->setGeometry(QRect(1540, 70, 52, 32));
        PerField->setValue(1);
        EndField = new QSpinBox(centralwidget);
        EndField->setObjectName(QString::fromUtf8("EndField"));
        EndField->setGeometry(QRect(1540, 120, 52, 32));
        EndField->setValue(1);
        ChaField = new QSpinBox(centralwidget);
        ChaField->setObjectName(QString::fromUtf8("ChaField"));
        ChaField->setGeometry(QRect(1540, 170, 52, 32));
        ChaField->setValue(1);
        IntField = new QSpinBox(centralwidget);
        IntField->setObjectName(QString::fromUtf8("IntField"));
        IntField->setGeometry(QRect(1540, 220, 52, 32));
        IntField->setValue(1);
        AgiField = new QSpinBox(centralwidget);
        AgiField->setObjectName(QString::fromUtf8("AgiField"));
        AgiField->setGeometry(QRect(1540, 270, 52, 32));
        AgiField->setValue(1);
        LucField = new QSpinBox(centralwidget);
        LucField->setObjectName(QString::fromUtf8("LucField"));
        LucField->setGeometry(QRect(1540, 320, 52, 32));
        LucField->setValue(1);
        label_18 = new QLabel(centralwidget);
        label_18->setObjectName(QString::fromUtf8("label_18"));
        label_18->setGeometry(QRect(960, 270, 58, 18));
        textEdit = new QTextEdit(centralwidget);
        textEdit->setObjectName(QString::fromUtf8("textEdit"));
        textEdit->setGeometry(QRect(623, 300, 741, 511));
        TotalActionsField = new QSpinBox(centralwidget);
        TotalActionsField->setObjectName(QString::fromUtf8("TotalActionsField"));
        TotalActionsField->setGeometry(QRect(1400, 440, 52, 32));
        TotalActionsField->setMinimum(1);
        TotalActionsField->setValue(4);
        pushButton = new QPushButton(centralwidget);
        pushButton->setObjectName(QString::fromUtf8("pushButton"));
        pushButton->setGeometry(QRect(1540, 710, 88, 34));
        UsedActionsField = new QSpinBox(centralwidget);
        UsedActionsField->setObjectName(QString::fromUtf8("UsedActionsField"));
        UsedActionsField->setGeometry(QRect(1490, 440, 52, 32));
        label_19 = new QLabel(centralwidget);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(1400, 410, 58, 18));
        label_20 = new QLabel(centralwidget);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(1490, 410, 58, 18));
        checkBox = new QCheckBox(centralwidget);
        checkBox->setObjectName(QString::fromUtf8("checkBox"));
        checkBox->setGeometry(QRect(1430, 720, 111, 22));
        label_21 = new QLabel(centralwidget);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(1640, 720, 58, 18));
        checkBox_2 = new QCheckBox(centralwidget);
        checkBox_2->setObjectName(QString::fromUtf8("checkBox_2"));
        checkBox_2->setGeometry(QRect(1590, 20, 111, 22));
        checkBox_3 = new QCheckBox(centralwidget);
        checkBox_3->setObjectName(QString::fromUtf8("checkBox_3"));
        checkBox_3->setGeometry(QRect(1590, 70, 111, 22));
        checkBox_4 = new QCheckBox(centralwidget);
        checkBox_4->setObjectName(QString::fromUtf8("checkBox_4"));
        checkBox_4->setGeometry(QRect(1590, 120, 101, 22));
        checkBox_5 = new QCheckBox(centralwidget);
        checkBox_5->setObjectName(QString::fromUtf8("checkBox_5"));
        checkBox_5->setGeometry(QRect(1590, 170, 101, 22));
        checkBox_6 = new QCheckBox(centralwidget);
        checkBox_6->setObjectName(QString::fromUtf8("checkBox_6"));
        checkBox_6->setGeometry(QRect(1590, 220, 101, 22));
        checkBox_7 = new QCheckBox(centralwidget);
        checkBox_7->setObjectName(QString::fromUtf8("checkBox_7"));
        checkBox_7->setGeometry(QRect(1590, 270, 111, 22));
        checkBox_8 = new QCheckBox(centralwidget);
        checkBox_8->setObjectName(QString::fromUtf8("checkBox_8"));
        checkBox_8->setGeometry(QRect(1590, 320, 111, 22));
        tableWidget_3 = new QTableWidget(centralwidget);
        tableWidget_3->setObjectName(QString::fromUtf8("tableWidget_3"));
        tableWidget_3->setGeometry(QRect(0, 310, 256, 192));
        tableWidget_4 = new QTableWidget(centralwidget);
        tableWidget_4->setObjectName(QString::fromUtf8("tableWidget_4"));
        tableWidget_4->setGeometry(QRect(270, 310, 256, 192));
        tableWidget_5 = new QTableWidget(centralwidget);
        tableWidget_5->setObjectName(QString::fromUtf8("tableWidget_5"));
        tableWidget_5->setGeometry(QRect(0, 550, 256, 192));
        tableView = new QTableView(centralwidget);
        tableView->setObjectName(QString::fromUtf8("tableView"));
        tableView->setGeometry(QRect(270, 550, 256, 192));
        label_22 = new QLabel(centralwidget);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(110, 280, 58, 18));
        label_23 = new QLabel(centralwidget);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(320, 280, 151, 18));
        label_24 = new QLabel(centralwidget);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(100, 520, 81, 18));
        pushButton_2 = new QPushButton(centralwidget);
        pushButton_2->setObjectName(QString::fromUtf8("pushButton_2"));
        pushButton_2->setGeometry(QRect(210, 780, 88, 34));
        label_25 = new QLabel(centralwidget);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(360, 520, 71, 18));
        CurrentDayField = new QSpinBox(centralwidget);
        CurrentDayField->setObjectName(QString::fromUtf8("CurrentDayField"));
        CurrentDayField->setGeometry(QRect(1400, 510, 52, 32));
        CurrentDayField->setMinimum(1);
        CurrentDayField->setMaximum(10);
        label_26 = new QLabel(centralwidget);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(1400, 490, 121, 18));
        spinBox = new QSpinBox(centralwidget);
        spinBox->setObjectName(QString::fromUtf8("spinBox"));
        spinBox->setGeometry(QRect(1450, 510, 52, 32));
        spinBox->setMinimum(1);
        spinBox->setMaximum(1000);
        TotalDaysField = new QSpinBox(centralwidget);
        TotalDaysField->setObjectName(QString::fromUtf8("TotalDaysField"));
        TotalDaysField->setGeometry(QRect(1430, 570, 52, 32));
        TotalDaysField->setMinimum(1);
        TotalDaysField->setValue(7);
        label_27 = new QLabel(centralwidget);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(1380, 550, 171, 18));
        label_28 = new QLabel(centralwidget);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(1600, 410, 81, 18));
        NumberOfActionsField1 = new QSpinBox(centralwidget);
        NumberOfActionsField1->setObjectName(QString::fromUtf8("NumberOfActionsField1"));
        NumberOfActionsField1->setGeometry(QRect(1600, 430, 52, 32));
        label_29 = new QLabel(centralwidget);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(1680, 410, 58, 18));
        label_30 = new QLabel(centralwidget);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(1740, 410, 58, 18));
        label_31 = new QLabel(centralwidget);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(1800, 410, 58, 18));
        lineEdit_4 = new QLineEdit(centralwidget);
        lineEdit_4->setObjectName(QString::fromUtf8("lineEdit_4"));
        lineEdit_4->setGeometry(QRect(1680, 430, 51, 32));
        lineEdit_5 = new QLineEdit(centralwidget);
        lineEdit_5->setObjectName(QString::fromUtf8("lineEdit_5"));
        lineEdit_5->setGeometry(QRect(1740, 430, 51, 32));
        lineEdit_6 = new QLineEdit(centralwidget);
        lineEdit_6->setObjectName(QString::fromUtf8("lineEdit_6"));
        lineEdit_6->setGeometry(QRect(1800, 430, 113, 32));
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName(QString::fromUtf8("menubar"));
        menubar->setGeometry(QRect(0, 0, 1919, 30));
        menuFile = new QMenu(menubar);
        menuFile->setObjectName(QString::fromUtf8("menuFile"));
        menuHelp = new QMenu(menubar);
        menuHelp->setObjectName(QString::fromUtf8("menuHelp"));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        menubar->addAction(menuFile->menuAction());
        menubar->addAction(menuHelp->menuAction());
        menuFile->addAction(actionNew_Character);
        menuFile->addAction(actionSave_Character);
        menuFile->addAction(actionSave_As);
        menuFile->addAction(actionLoad_Character);
        menuFile->addSeparator();
        menuFile->addAction(actionExit);
        menuHelp->addAction(actionAbout);
        menuHelp->addAction(actionAbout_Qt);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
        actionNew_Character->setText(QApplication::translate("MainWindow", "&New Character", nullptr));
        actionSave_Character->setText(QApplication::translate("MainWindow", "&Save Character", nullptr));
        actionLoad_Character->setText(QApplication::translate("MainWindow", "&Load Character", nullptr));
        actionExit->setText(QApplication::translate("MainWindow", "&Exit", nullptr));
        actionAbout->setText(QApplication::translate("MainWindow", "&About", nullptr));
        actionAbout_Qt->setText(QApplication::translate("MainWindow", "About &Qt", nullptr));
        actionSave_As->setText(QApplication::translate("MainWindow", "Save &Character As", nullptr));
        nameInputField->setText(QApplication::translate("MainWindow", "Name", nullptr));
        organizationInputField->setText(QApplication::translate("MainWindow", "Organization", nullptr));
        CampaignInputField->setText(QApplication::translate("MainWindow", "Campaign", nullptr));
        label->setText(QApplication::translate("MainWindow", "Harm", nullptr));
        label_2->setText(QApplication::translate("MainWindow", "Stress", nullptr));
        label_3->setText(QApplication::translate("MainWindow", "Mental Harm", nullptr));
        label_4->setText(QApplication::translate("MainWindow", "Spiritual Harm", nullptr));
        label_5->setText(QApplication::translate("MainWindow", "Willpower", nullptr));
        WillpowerField->setText(QApplication::translate("MainWindow", "10", nullptr));
        label_6->setText(QApplication::translate("MainWindow", "Heat", nullptr));
        HeatField->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_7->setText(QApplication::translate("MainWindow", "Favor", nullptr));
        FavorField->setText(QApplication::translate("MainWindow", "0", nullptr));
        label_8->setText(QApplication::translate("MainWindow", "Cores", nullptr));
        AddCoresButton->setText(QApplication::translate("MainWindow", "Add Cores", nullptr));
        label_9->setText(QApplication::translate("MainWindow", "Spells", nullptr));
        AddSpellButton->setText(QApplication::translate("MainWindow", "Add Spell", nullptr));
        label_10->setText(QApplication::translate("MainWindow", "Stats", nullptr));
        label_11->setText(QApplication::translate("MainWindow", "STR", nullptr));
        label_12->setText(QApplication::translate("MainWindow", "PER", nullptr));
        label_13->setText(QApplication::translate("MainWindow", "END", nullptr));
        label_14->setText(QApplication::translate("MainWindow", "CHA", nullptr));
        label_15->setText(QApplication::translate("MainWindow", "INT", nullptr));
        label_16->setText(QApplication::translate("MainWindow", "AGI", nullptr));
        label_17->setText(QApplication::translate("MainWindow", "LUC", nullptr));
        label_18->setText(QApplication::translate("MainWindow", "Notes", nullptr));
        pushButton->setText(QApplication::translate("MainWindow", "Roll", nullptr));
        label_19->setText(QApplication::translate("MainWindow", "Actions", nullptr));
        label_20->setText(QApplication::translate("MainWindow", "Used", nullptr));
        checkBox->setText(QApplication::translate("MainWindow", "Use Action?", nullptr));
        label_21->setText(QApplication::translate("MainWindow", "Result: ", nullptr));
        checkBox_2->setText(QApplication::translate("MainWindow", "Use in Roll", nullptr));
        checkBox_3->setText(QApplication::translate("MainWindow", "Use in Roll", nullptr));
        checkBox_4->setText(QApplication::translate("MainWindow", "Use in Roll", nullptr));
        checkBox_5->setText(QApplication::translate("MainWindow", "Use in Roll", nullptr));
        checkBox_6->setText(QApplication::translate("MainWindow", "Use in Roll", nullptr));
        checkBox_7->setText(QApplication::translate("MainWindow", "Use in Roll", nullptr));
        checkBox_8->setText(QApplication::translate("MainWindow", "Use in Roll", nullptr));
        label_22->setText(QApplication::translate("MainWindow", "Perks", nullptr));
        label_23->setText(QApplication::translate("MainWindow", "Obsessions/Psychosis", nullptr));
        label_24->setText(QApplication::translate("MainWindow", "Blessings", nullptr));
        pushButton_2->setText(QApplication::translate("MainWindow", "Add", nullptr));
        label_25->setText(QApplication::translate("MainWindow", "Inventory", nullptr));
        label_26->setText(QApplication::translate("MainWindow", "Current Day/Week", nullptr));
        label_27->setText(QApplication::translate("MainWindow", "Number of Days in a week", nullptr));
        label_28->setText(QApplication::translate("MainWindow", "# of Actions", nullptr));
        label_29->setText(QApplication::translate("MainWindow", "Modifier", nullptr));
        label_30->setText(QApplication::translate("MainWindow", "Progress", nullptr));
        label_31->setText(QApplication::translate("MainWindow", "Upgrade", nullptr));
        menuFile->setTitle(QApplication::translate("MainWindow", "Fi&le", nullptr));
        menuHelp->setTitle(QApplication::translate("MainWindow", "Help", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // MAINWINDOWMFTMBC_H
